# scrape.utils.hepsiburada package facade that keeps the module-level API

from ..trendyol.common import (
    _extract_first_string,
    _format_price_value,
    _is_placeholder_description_text,
    _iter_json_ld_payloads,
    _normalize_json_value,
    _safe_api_call,
    _str,
    parse_html,
    product_dataset_to_json,
)
from .api import *
from .builders import *
from .dataset import *
from .http import *
from .parsing import *

__all__: list[str] = [
    "_HEPB_UA",
    "_META_FIELDS",
    "_HepbAPIContext",
    "_api_headers",
    "_build_ask_to_seller",
    "_build_description",
    "_build_discount_rate",
    "_build_installment_offer",
    "_build_other_merchants",
    "_build_payment_options",
    "_build_pricing",
    "_build_shipping",
    "_build_vas",
    "_build_without_affordability",
    "_clean_description_text",
    "_detect_category",
    "_extract_attribute_fallback_description",
    "_extract_availability",
    "_extract_custom_data",
    "_extract_description_from_dom",
    "_extract_first_string",
    "_extract_image",
    "_extract_product_ctx",
    "_extract_product_from_json_ld",
    "_extract_redux_product",
    "_extract_redux_store",
    "_format_price_value",
    "_goto_referer",
    "_is_generic_hepsiburada_description",
    "_is_hepb_response_dict",
    "_is_placeholder_description_text",
    "_iter_json_ld_payloads",
    "_kurus_amount",
    "_listing_price_value",
    "_merge_product_meta",
    "_normalize_json_value",
    "_safe_api_call",
    "_str",
    "_strip_placeholder_tokens",
    "_to_int_list",
    "build_product_dataset",
    "extract_price",
    "extract_product_data",
    "extract_product_dataset",
    "get_ask_to_seller_from_api",
    "get_installment_from_api",
    "get_listings_from_api",
    "get_other_merchants_from_api",
    "get_payment_options_from_api",
    "get_raw_html",
    "get_shipping_due_date_from_api",
    "get_vas_from_api",
    "get_without_affordability_from_api",
    "parse_html",
    "product_dataset_to_json",
    "requests",
]
